In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
import os

filename = 'healthcare_dataset.csv'
root_dir = '/workspaces/Synthetic-Healthcare-Data-Analysis-/'

for root, dirs, files in os.walk(root_dir):
    if filename in files:
        path = os.path.join(root, filename)
        print(path)
    print("file name not found.")

/workspaces/Synthetic-Healthcare-Data-Analysis-/healthcare_dataset.csv

In [6]:
df = pd.read_csv(path) 
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive

# Data Transformation

- Lower case name
- Sort by name
- Lower case column name & Replace space with _
- Remove any duplications by subset of columns: name, date of admission, doctor, discharge date
- Replace name to index number as a unique id

### NOTE

The data doesn't contain person identity, therefore cannot provide unique id at this point with the given informations.

In [7]:
df['Name'] = df['Name'].str.lower()
df_sorted = df.sort_values(by = ['Name'])
df_sorted

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
22276,aaron adams,38,Female,O-,Cancer,2021-03-10,Norma Li,Hart LLC,UnitedHealthcare,26052.106404,363,Elective,2021-03-29,Lipitor,Inconclusive
16314,aaron aguirre,36,Male,A-,Diabetes,2023-02-26,Katrina Luna,Murray-Shelton,UnitedHealthcare,27087.560553,300,Emergency,2023-03-13,Aspirin,Inconclusive
49453,aaron anderson,50,Female,A+,Asthma,2020-12-18,Kenneth Jennings,Tanner-Cox,Cigna,39804.658624,196,Urgent,2021-01-15,Aspirin,Inconclusive
18884,aaron anderson md,20,Female,A-,Hypertension,2021-03-28,Tammy Perez,Ritter LLC,UnitedHealthcare,16846.415799,249,Elective,2021-04-09,Paracetamol,Abnormal
3040,aaron archer,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21678,zoe jackson,38,Male,A-,Asthma,2021-07-25,Andrew Hall,Jones PLC,Aetna,16668.258866,476,Urgent,2021-07-30,Aspirin,Inconclusive
55045,zoe rodriguez,53,Female,O+,Cancer,2024-03-22,David Keller,Jones Ltd,Medicare,9024.092301,178,Elective,2024-04-08,Penicillin,Inconclusive
41646,zoe rodriguez,53,Female,O+,Cancer,2024-03-22,David Keller,Jones Ltd,Medicare,9024.092301,178,Elective,2024-04-08,Penicillin,Inconclusive
14694,zoe smith,36,Male,AB-,Obesity,2022-02-24,Mary Bates,Inc Morales,Aetna,33252.225130,272,Emergency,2022-03-15,Penicillin,Inconclusive
43200,zoe white,25,Female,AB+,Diabetes,2020-05-29,Heidi Kennedy,Ltd Estes,Medicare,28747.964184,267,Emergency,2020-05-30,Ibuprofen,Normal

In [15]:
df_sorted.columns = df_sorted.columns.str.lower().str.replace(" ", "_")

In [16]:
df_sorted[df_sorted.duplicated()]

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
42407,abigail young,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
40385,adam thomas,75,Male,O+,Hypertension,2022-01-02,Beverly Miller,Sanchez-Wilson,Cigna,16294.907725,180,Urgent,2022-01-30,Ibuprofen,Normal
55298,alex black,51,Male,O+,Diabetes,2022-03-27,Frank Williams,Short and Sons,Aetna,39525.674902,246,Emergency,2022-04-21,Aspirin,Normal
31845,alexandra santiago,53,Male,B-,Arthritis,2024-01-17,Donald Solis,"and White, Wall Hurst",UnitedHealthcare,4177.715918,450,Urgent,2024-02-15,Penicillin,Normal
16386,alfred cervantes,65,Male,AB-,Diabetes,2023-12-24,Linda Hall,Dorsey Ltd,Aetna,1903.879223,385,Elective,2024-01-04,Paracetamol,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16881,william savage,30,Female,O-,Asthma,2019-12-11,Veronica Smith,Bennett-Brooks,Medicare,24502.672173,496,Elective,2019-12-12,Paracetamol,Inconclusive
11582,willie schwartz,49,Female,A-,Arthritis,2019-08-16,Lori Hughes,Schmidt-Ford,Medicare,32612.697020,304,Elective,2019-09-02,Paracetamol,Normal
24049,willie small,67,Female,A+,Arthritis,2023-07-25,Susan Gordon,Stone-West,Aetna,29898.351551,451,Emergency,2023-08-04,Penicillin,Abnormal
51964,zachary ball,85,Female,B-,Diabetes,2020-04-25,Matthew Conley,"and Morgan Jones, Matthews",Blue Cross,15207.547262,202,Emergency,2020-05-25,Penicillin,Inconclusive
41646,zoe rodriguez,53,Female,O+,Cancer,2024-03-22,David Keller,Jones Ltd,Medicare,9024.092301,178,Elective,2024-04-08,Penicillin,Inconclusive

In [18]:
df_clean = df_sorted.drop_duplicates(subset = ['name', 'medical_condition', 'date_of_admission', 'doctor', 'discharge_date'])
df_clean

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
22276,aaron adams,38,Female,O-,Cancer,2021-03-10,Norma Li,Hart LLC,UnitedHealthcare,26052.106404,363,Elective,2021-03-29,Lipitor,Inconclusive
16314,aaron aguirre,36,Male,A-,Diabetes,2023-02-26,Katrina Luna,Murray-Shelton,UnitedHealthcare,27087.560553,300,Emergency,2023-03-13,Aspirin,Inconclusive
49453,aaron anderson,50,Female,A+,Asthma,2020-12-18,Kenneth Jennings,Tanner-Cox,Cigna,39804.658624,196,Urgent,2021-01-15,Aspirin,Inconclusive
18884,aaron anderson md,20,Female,A-,Hypertension,2021-03-28,Tammy Perez,Ritter LLC,UnitedHealthcare,16846.415799,249,Elective,2021-04-09,Paracetamol,Abnormal
3040,aaron archer,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17312,zoe black,77,Female,A-,Diabetes,2022-09-24,Robert Nguyen,"Lawrence and Bean Barton,",Blue Cross,21654.260701,247,Elective,2022-10-01,Penicillin,Abnormal
21678,zoe jackson,38,Male,A-,Asthma,2021-07-25,Andrew Hall,Jones PLC,Aetna,16668.258866,476,Urgent,2021-07-30,Aspirin,Inconclusive
55045,zoe rodriguez,53,Female,O+,Cancer,2024-03-22,David Keller,Jones Ltd,Medicare,9024.092301,178,Elective,2024-04-08,Penicillin,Inconclusive
14694,zoe smith,36,Male,AB-,Obesity,2022-02-24,Mary Bates,Inc Morales,Aetna,33252.225130,272,Emergency,2022-03-15,Penicillin,Inconclusive
43200,zoe white,25,Female,AB+,Diabetes,2020-05-29,Heidi Kennedy,Ltd Estes,Medicare,28747.964184,267,Emergency,2020-05-30,Ibuprofen,Normal

In [19]:
df_clean = df_clean.reset_index().drop(labels = 'index', axis = 1)
df_clean.head(10)

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,aaron adams,38,Female,O-,Cancer,2021-03-10,Norma Li,Hart LLC,UnitedHealthcare,26052.106404,363,Elective,2021-03-29,Lipitor,Inconclusive
1,aaron aguirre,36,Male,A-,Diabetes,2023-02-26,Katrina Luna,Murray-Shelton,UnitedHealthcare,27087.560553,300,Emergency,2023-03-13,Aspirin,Inconclusive
2,aaron anderson,50,Female,A+,Asthma,2020-12-18,Kenneth Jennings,Tanner-Cox,Cigna,39804.658624,196,Urgent,2021-01-15,Aspirin,Inconclusive
3,aaron anderson md,20,Female,A-,Hypertension,2021-03-28,Tammy Perez,Ritter LLC,UnitedHealthcare,16846.415799,249,Elective,2021-04-09,Paracetamol,Abnormal
4,aaron archer,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive
5,aaron baker,84,Female,A+,Asthma,2022-06-04,Brittany Smith,"Carter, Abbott and Fuentes",Medicare,6826.677363,496,Emergency,2022-06-10,Lipitor,Normal
6,aaron baker,73,Male,B+,Cancer,2019-06-18,Tracy Torres,"Wise and Todd, Parker",Medicare,10135.885442,234,Elective,2019-07-10,Aspirin,Inconclusive
7,aaron baldwin jr.,20,Male,O-,Hypertension,2020-10-10,Amy Farley,"Flores Friedman and White,",Medicare,29740.960199,104,Urgent,2020-11-05,Paracetamol,Abnormal
8,aaron barnes,85,Male,O-,Obesity,2023-03-30,Vincent Johnson,Taylor LLC,UnitedHealthcare,4783.444339,136,Urgent,2023-04-20,Ibuprofen,Normal
9,aaron bautista,21,Male,B-,Hypertension,2023-09-24,Ashley Chandler,Duarte-Baker,UnitedHealthcare,49827.519768,465,Urgent,2023-10-24,Aspirin,Inconclusive

In [20]:
df_clean[df_clean.duplicated()]

Empty DataFrame
Columns: [name, age, gender, blood_type, medical_condition, date_of_admission, doctor, hospital, insurance_provider, billing_amount, room_number, admission_type, discharge_date, medication, test_results]
Index: []

# Loading date into a datebase

- using SQlite

In [21]:
import sqlite3
conn = sqlite3.connect('database.db')

In [22]:
df_clean.to_sql('healthcare_dataset_table', conn, if_exists='replace', index=False)

50000